spring.application.name=electrocorp-platform

server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/electrocorp_db}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.naming.physical-strategy=com.electrocorp.electrocorpplatform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy

spring.jackson.time-zone=America/Lima